### PR TITLE
Fix Python 3.10 compatibility

### PR DESCRIPTION
**Pull request by awsr**
Force some values to `int` in order to prevent TypeError caused by changes to Python 3.10. (Most likely caused by https://github.com/python/cpython/issues/82180)

### CODE REVIEW

**Comment by bluaxees** [comment]
Do you have the build file for this? The current build file I have doesn't work with this branch

**Comment by awsr** [comment]
I don't have a build file because I didn't even notice the `main.spec` file in the release assets until just now. I've just been running `main.py` directly from a batch file.
Is it giving a specific error or does it just not work with other branches?

**Comment by awsr** [comment]
I have also considered including the following addition to `README.md` before the "System Requirements" section to remind people to get the correct version of `tesserocr` if developing on Windows:
```markdown
#### For Developers on Windows
*Before installing the requirements*, you must download a [pre-compiled build of tesserocr](https://github.com/simonflueckiger/tesserocr-windows_build/releases) and install it: `pip install <package_name>.whl`
```

**Comment by bluaxees** [comment]
I don't think this is an issue on `tesseract`. It might be due to `torch` which only added 3.10 support last year

**Comment by bluaxees** [comment]
Merging this on a dev branch, since I can't build the app with python 3.10

**Pull request merged**
